sysimibio/imibio_tree_ecological_data/urls.py
from django.urls import path
from django.views.generic import TemplateView

from sysimibio.imibio_tree_ecological_data.views import (
    trees_geojson,
    PlotListView,
    PlotDetailView,
    PlotDetailGeoJson,
    PlotCreateView,
    PlotEditView,
    FieldWorkListView,
    FieldWorkDetailView,
    FieldWorkEditView,
    FieldWorkCreateView,
    TreeCreateView,
    TreeDetailView,
    TreeDetailGeoJson,
    TreeEditView,
    TreeListView,
    TreeMeasurementCreateView,
    TreeMeasurementDetailView,
    TreeMeasurementEditView,
    TreeMeasurementListView,
    PlotDetailTreesGeoJson,
    FieldWorkDetailTreesGeoJson,
)

app_name = "imibio_tree_ecological_data"

urlpatterns = [
    # plot
    path("create/plot/", PlotCreateView, name="plot_create"),
    path("edit/plot/<int:pk>/", PlotEditView, name="plot_edit"),
    path("list/plot/", PlotListView, name="plot_list"),
    path("detail/plot/<int:pk>/", PlotDetailView, name="plot_detail"),
    path("geojson/plot/<int:pk>/", PlotDetailGeoJson, name="plot_detail_geojson"),
    path(
        "geojson/plot/<int:pk>/trees",
        PlotDetailTreesGeoJson,
        name="trees_plot_detail_geojson",
    ),
    # field work
    path("create/field/", FieldWorkCreateView, name="field_create"),
    path("edit/field/<int:pk>/", FieldWorkEditView, name="field_edit"),
    path("list/field/", FieldWorkListView, name="field_list"),
    path("detail/field/<int:pk>/", FieldWorkDetailView, name="field_detail"),
    path(
        "geojson/field/<int:pk>/trees",
        FieldWorkDetailTreesGeoJson,
        name="trees_field_detail_geojson",
    ),
    # tree
    path("create/tree/", TreeCreateView, name="tree_create"),
    path("edit/tree/<int:pk>/", TreeEditView, name="tree_edit"),
    path("list/tree/", TreeListView, name="tree_list"),
    path("detail/tree/<int:pk>/", TreeDetailView, name="tree_detail"),
    path("geojson/tree/<int:pk>/", TreeDetailGeoJson, name="Tree_detail_geojson"),
    # tree measurement
    path(
        "create/tree/measurement/",
        TreeMeasurementCreateView,
        name="tree_measurement_create",
    ),
    path(
        "edit/tree/measurement/<int:pk>/",
        TreeMeasurementEditView,
        name="tree_measurement_edit",
    ),
    path(
        "list/tree/measurement/", TreeMeasurementListView, name="tree_measurement_list"
    ),
    path(
        "detail/tree/measurement/<int:pk>/",
        TreeMeasurementDetailView,
        name="tree_measurement_detail",
    ),
    # general
    path("geojson/", trees_geojson, name="data"),
    path("map/", TemplateView.as_view(template_name="tree_map.html"), name="map"),
]

sysimibio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sysimibio.core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sysimibio.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", home, name="home"),
    path(
        "imibio_occurrences/", include("sysimibio.imibio_occurrences.urls")
    ),  # todo cambiar a ingles
    path(
        "imibio_tree_ecological_data/",
        include("sysimibio.imibio_tree_ecological_data.urls"),
    ),  # todo cambiar a ingles
    path("bioblitz/", include("sysimibio.bioblitz.urls")),
    path("bibliography/", include("sysimibio.bibliography.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/imibio_tree_ecological_data/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django_filters.views import FilterView
from djgeojson.views import GeoJSONLayerView

from sysimibio.imibio_tree_ecological_data.filters import TreeMeasurementFilters
from sysimibio.imibio_tree_ecological_data.forms import (
    TreeForm,
    FieldForm,
    PermanentParcelForm,
    TreeMeasurementForm,
)
from sysimibio.imibio_tree_ecological_data.models import (
    FieldWork,
    Tree,
    PermanentParcel,
    TreeMeasurement,
)


class PlotCreateView(LoginRequiredMixin, CreateView):
    model = PermanentParcel
    form_class = PermanentParcelForm

    def post(self, request, *args, **kwargs):
        form = PermanentParcelForm(request.POST)
        if form.is_valid():
            self.object.save()
            return redirect("imibio_tree_ecological_data:plot_detail", self.object.pk)
        else:
            return render(
                self.request,
                "imibio_tree_ecological_data/permanentparcel_form.html",
                {"form": form},
            )


PlotCreateView = PlotCreateView.as_view()


class PlotEditView(LoginRequiredMixin, UpdateView):
    model = PermanentParcel
    form_class = PermanentParcelForm

    def post(self, request, *args, **kwargs):
        pk = self.kwargs["pk"]
        parcel = get_object_or_404(PermanentParcel, pk=pk)
        form = PermanentParcelForm(request.POST, instance=parcel)
        if form.is_valid():
            form.save()
            return redirect("imibio_tree_ecological_data:plot_detail", pk)
        else:
            return render(
                self.request,
                "imibio_tree_ecological_data/permanentparcel_form.html",
                {"form": form},
            )


PlotEditView = PlotEditView.as_view()


class PlotListView(LoginRequiredMixin, ListView):
    model = PermanentParcel


PlotListView = PlotListView.as_view()


class PlotDetailView(LoginRequiredMixin, DetailView):
    model = PermanentParcel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["field_list"] = FieldWork.objects.filter(parcel_id=self.kwargs["pk"])
        context["measurement_list"] = TreeMeasurement.objects.filter(
            tree__field__parcel_id=self.kwargs["pk"]
        )
        context["tree_list"] = Tree.objects.filter(field__parcel_id=self.kwargs["pk"])
        return context


PlotDetailView = PlotDetailView.as_view()


class PlotDetailGeoJson(GeoJSONLayerView):
    model = PermanentParcel
    properties = ("popup_content",)

    def get_queryset(self):
        self.plot = super().get_queryset()
        return self.plot.filter(pk=self.kwargs["pk"])


PlotDetailGeoJson = PlotDetailGeoJson.as_view()


class PlotDetailTreesGeoJson(GeoJSONLayerView):
    model = Tree
    properties = ("popup_content",)

    def get_queryset(self):
        self.tree = super().get_queryset()
        return self.tree.filter(field__parcel_id=self.kwargs["pk"])


PlotDetailTreesGeoJson = PlotDetailTreesGeoJson.as_view()


class FieldWorkCreateView(LoginRequiredMixin, CreateView):
    model = FieldWork
    form_class = FieldForm


FieldWorkCreateView = FieldWorkCreateView.as_view()


class FieldWorkEditView(LoginRequiredMixin, UpdateView):
    model = FieldWork
    form_class = FieldForm


FieldWorkEditView = FieldWorkEditView.as_view()


class FieldWorkListView(LoginRequiredMixin, ListView):
    model = FieldWork


FieldWorkListView = FieldWorkListView.as_view()


class FieldWorkDetailView(LoginRequiredMixin, DetailView):
    model = FieldWork

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["measurement_list"] = TreeMeasurement.objects.filter(
            tree__field__pk=self.kwargs["pk"]
        )
        context["tree_list"] = Tree.objects.filter(field__pk=self.kwargs["pk"])
        return context


FieldWorkDetailView = FieldWorkDetailView.as_view()


class FieldWorkDetailTreesGeoJson(GeoJSONLayerView):
    model = Tree
    properties = ("popup_content",)

    def get_queryset(self):
        self.tree = super().get_queryset()
        return self.tree.filter(field__pk=self.kwargs["pk"])


FieldWorkDetailTreesGeoJson = FieldWorkDetailTreesGeoJson.as_view()


class TreeCreateView(LoginRequiredMixin, CreateView):
    model = Tree
    form_class = TreeForm


TreeCreateView = TreeCreateView.as_view()


class TreeEditView(LoginRequiredMixin, UpdateView):
    model = Tree
    form_class = TreeForm


TreeEditView = TreeEditView.as_view()


class TreeListView(LoginRequiredMixin, ListView):
    model = Tree


TreeListView = TreeListView.as_view()


class TreeDetailView(LoginRequiredMixin, DetailView):
    model = Tree

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["measurement_list"] = TreeMeasurement.objects.filter(
            tree__pk=self.kwargs["pk"]
        )
        return context


TreeDetailView = TreeDetailView.as_view()


class TreeDetailGeoJson(GeoJSONLayerView):
    model = Tree
    properties = ("popup_content",)

    def get_queryset(self):
        self.tree = super().get_queryset()
        return self.tree.filter(pk=self.kwargs["pk"])


TreeDetailGeoJson = TreeDetailGeoJson.as_view()


class TreeMeasurementCreateView(LoginRequiredMixin, CreateView):
    model = TreeMeasurement
    form_class = TreeMeasurementForm


TreeMeasurementCreateView = TreeMeasurementCreateView.as_view()


class TreeMeasurementEditView(LoginRequiredMixin, UpdateView):
    model = TreeMeasurement
    form_class = TreeMeasurementForm


TreeMeasurementEditView = TreeMeasurementEditView.as_view()


class TreeMeasurementListView(LoginRequiredMixin, FilterView):
    model = TreeMeasurement
    queryset = TreeMeasurement.objects.all().order_by("-created_at")
    filterset_class = TreeMeasurementFilters
    template_name = "imibio_tree_ecological_data/treemeasurement_list.html"


TreeMeasurementListView = TreeMeasurementListView.as_view()


class TreeMeasurementDetailView(LoginRequiredMixin, DetailView):
    model = TreeMeasurement


TreeMeasurementDetailView = TreeMeasurementDetailView.as_view()


class TreesGeoJson(GeoJSONLayerView):
    model = Tree
    properties = ("popup_content",)


trees_geojson = TreesGeoJson.as_view()

sysimibio/imibio_tree_ecological_data/templates/imibio_tree_ecological_data/fieldwork_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
{% leaflet_js %}
{% endblock %}

{% block css %}
{% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }

</style>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}


<br>
<div class="row">
    <a role="button" class="btn btn-success btn-lg" href="{% url 'imibio_tree_ecological_data:field_list' %}">
        <span class="align-middle">Lista de campos</span>
    </a>
    <a role="button" class="btn btn-warning btn-lg"
       href="{% url 'imibio_tree_ecological_data:field_edit' pk=object.pk %}">
        <span class="align-middle">Editar campo</span>
    </a>
</div>
<h2>Detalles del campo:</h2>
<div class="row">
    <div class="col-sm-4">
        <table class="table table-user-information">
            <tbody>
            <tr>
                <th class="text-right">Parcela permanente investigada</th>
                <td>{{ object.parcel_id }}</td>
            </tr>

            <tr>
                <th class="text-right">Coordinador(a)</th>
                <td>{{ object.coordinator }}</td>
            </tr>

            <tr>
                <th class="text-right">Staff</th>
                <td>{{ object.staff.all|join:", " }}</td>
            </tr>

            <tr>
                <th class="text-right">Fecha</th>
                <td>{{ object.date }}</td>
            </tr>

            <tr>
                <th class="text-right">Inicio</th>
                <td>{{ object.start_time }}</td>
            </tr>

            <tr>
                <th class="text-right">Fin</th>
                <td>{{ object.end_time }}</td>
            </tr>

            <tr>
                <th class="text-right">Temperatura</th>
                <td>{{ object.temperature }}</td>
            </tr>

            <tr>
                <th class="text-right">Humedad</th>
                <td>{{ object.humidity }}</td>
            </tr>

            </tbody>
        </table>

    </div>

    <div class="col-sm-8">
        <div id="map-detail">
            {% leaflet_map "map-detail" %}
        </div>
    </div>
</div>
<div class="row">
    <div class="jumbotron">
    <div class="col-fluid">
        <h2>Lista individuos arbóreos</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>ID</th>
            <th>specie</th>
            <th>Fecha registro</th>
        </tr>
        </thead>

        {% for tree in tree_list %}
        <tr>
            <td>
                <a href="{{ tree.get_absolute_url }}">{{ tree.tree_id }}</a>
            </td>
            <td>{{ tree.specie }}</td>
            <td>{{ tree.created_at }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
    <div style="background:transparent" class="jumbotron">
    <div class="col-fluid">
        <h2>Lista mediciones</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>ID</th>
            <th>Individuo</th>
            <th>DAB</th>
            <th>DAP</th>
            <th>Altura</th>
        </tr>
        </thead>

        {% for measure in measurement_list %}
        <tr>
            <td>
                <a href="{{ measure.get_absolute_url }}">{{ measure }}</a>
            </td>
            <td>{{ measure.tree.specie }}</td>
            <td>{{ measure.dab }}</td>
            <td>{{ measure.dap }}</td>
            <td>{{ measure.tree_height }}</td>

        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
</div>

<script>
      var dataurl = '{% url "imibio_tree_ecological_data:plot_detail_geojson" pk=object.parcel_id.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
                 map.fitBounds(layer.getBounds(), { maxZoom: 15 });
            }}).addTo(map);
          });
      });

      var TreesFieldDetailGeoJson = '{% url "imibio_tree_ecological_data:trees_field_detail_geojson" pk=object.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(TreesFieldDetailGeoJson)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });

</script>


{% endblock content %}

sysimibio/imibio_tree_ecological_data/templates/imibio_tree_ecological_data/fieldwork_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<!-- todo configurar crispy para organizar los campos -->
{% block content %}

<div class="jumbotron">
    <div class="container">
        <a role="button" class="btn btn-success btn-lg" href="{% url 'imibio_tree_ecological_data:field_list' %}">
            <span class="align-middle">Volver</span>
        </a>
        <h2>Registro de visitas a campo</h2>
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
            <p>{{ message }}</p>
        </div>
        {% else %}
        <div class="alert alert-success" role="alert">
            <p>{{ message }}</p>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}

        <div class="accordion" id="accordionExample">
            <form method="POST" action="." class="post-form">
                {% csrf_token %}

                {% crispy form %}



            </form>
        </div>
    </div>
</div>

{% endblock %}

sysimibio/imibio_tree_ecological_data/templates/imibio_tree_ecological_data/permanentparcel_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
{% leaflet_js %}
{% endblock %}

{% block css %}
{% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }

</style>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}


<br>
<div class="row">
    <a role="button" class="btn btn-success btn-lg" href="{% url 'imibio_tree_ecological_data:plot_list' %}">
        <span class="align-middle">Lista de Parcelas</span>
    </a>
    <a role="button" class="btn btn-warning btn-lg"
       href="{% url 'imibio_tree_ecological_data:plot_edit' pk=object.pk %}">
        <span class="align-middle">Editar Parcela</span>
    </a>
</div>
    <h2>Detalles de la parcela: {{ object.name }}</h2>
<div class="row">
    <div class="col-sm-4">
        <table class="table table-user-information">
            <tbody>

            <tr>
                <th class="text-right">Nombre de la parcela</th>
                <td>{{ object.name }}</td>
            </tr>

            <tr>
                <th class="text-right">Coordinador(a)</th>
                <td>{{ object.coordinator }}</td>
            </tr>

            <tr>
                <th class="text-right">Provincia</th>
                <td>{{ object.province }}</td>
            </tr>

            <tr>
                <th class="text-right">Municipio</th>
                <td>{{ object.municipality }}</td>
            </tr>

            <tr>
                <th class="text-right">Lugar</th>
                <td>{{ object.locality }}</td>
            </tr>
            <tr>
                <th class="text-right">Nomenclatura catastral</th>
                <td>{{ object.cadastral_parcel }}</td>
            </tr>
            <tr>
                <th class="text-right">Tipo de parcela</th>

                <td>{{ object.plot_type | join:" y "}}</td>

            </tr>
            <tr>
                <th class="text-right">Fecha de creación</th>
                <td>{{ object.created_at }}</td>
            </tr>

            <tr>
                <th class="text-right">Observaciones</th>
                <td>{{ object.obs|linebreaks }}</td>

            </tr>

            </tbody>
        </table>

    </div>

    <div class="col-sm-8">
        <div id="map-detail">
            {% leaflet_map "map-detail" %}
        </div>
    </div>
</div>
<div class="row">
    <div class="jumbotron">
    <div class="col-fluid">
        <h2>Lista Visitas de campo</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>Parcela</th>
            <th>Fecha</th>
            <th>Inicio</th>
            <th>Coordenador</th>
            <th>Apoyo</th>

        </tr>
        </thead>

        {% for field in field_list %}
        <tr>
            <td>
                <a href="{{ field.get_absolute_url }}">{{ field }}</a>
            </td>
            <td>{{ field.date }}</td>
            <td>{{ field.start_time }}</td>
            <td>{{ field.coordinator }}</td>
            <td>{{ field.staff.all|join:", " }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
    <div style="background:transparent" class="jumbotron">
    <div class="col-fluid">
        <h2>Lista individuos arbóreos</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>ID</th>
            <th>specie</th>
            <th>str</th>
        </tr>
        </thead>

        {% for tree in tree_list %}
        <tr>
            <td>
                <a href="{{ tree.get_absolute_url }}">{{ tree.tree_id }}</a>
            </td>
            <td>{{ tree.specie }}</td>
            <td>{{ tree }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
</div>
<div class="row">
    <div style="background:transparent" class="jumbotron">
    <div class="col-fluid">
        <h2>Lista mediciones de árboles</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>Medición</th>
            <th>Árbol</th>
            <th>Fecha</th>
            <th>DAP</th>
            <th>DAB</th>

        </tr>
        </thead>

        {% for measure in measurement_list %}
        <tr>
            <td>
                <a href="{{ measure.get_absolute_url }}">{{ measure }}</a>
            </td>
            <td>{{ measure.tree }}</td>
            <td>{{ measure.created_at }}</td>
            <td>{{ measure.dap }}</td>
            <td>{{ measure.dab }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
</div>
<script>
      var dataurl = '{% url "imibio_tree_ecological_data:plot_detail_geojson" pk=object.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
                 map.fitBounds(layer.getBounds(), { maxZoom: 15 });
            }}).addTo(map);
          });
      });
      var TreesPlotDetailGeoJson = '{% url "imibio_tree_ecological_data:trees_plot_detail_geojson" pk=object.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(TreesPlotDetailGeoJson)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });

</script>


{% endblock content %}

sysimibio/imibio_tree_ecological_data/templates/imibio_tree_ecological_data/tree_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
{% leaflet_js %}
{% endblock %}

{% block css %}
{% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }

</style>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}


<br>
<div class="row">
    <a role="button" class="btn btn-success btn-lg" href="{% url 'imibio_tree_ecological_data:tree_list' %}">
        <span class="align-middle">Lista de árboles</span>
    </a>
    <a role="button" class="btn btn-warning btn-lg"
       href="{% url 'imibio_tree_ecological_data:tree_edit' pk=object.pk %}">
        <span class="align-middle">Editar árbol</span>
    </a>
</div>
<div class="row">

</div>
<h2>Detalles del Árbol: {{ object.tree_id }}</h2>
<div class="row">
    <div class="col-sm-4">
        <table class="table table-user-information">
            <tbody>

            <tr>
                <th class="text-right">Campo de registro</th>
                <td>{{ object.field }}</td>
            </tr>

            <tr>
                <th class="text-right">Parcela Permanente</th>
                <td>{{ object.field.parcel_id }}</td>
            </tr>

            <tr>
                <th class="text-right">Sub Parcale</th>
                <td>{{ object.subplot }}</td>
            </tr>

            <tr>
                <th class="text-right">Numero del àrbol</th>
                <td>{{ object.tree_number }}</td>
            </tr>

            <tr>
                <th class="text-right">Nombre de la especie</th>
                <td>{{ object.specie }}</td>
            </tr>

            <tr>
                <th class="text-right">Observaciones</th>
                <td>{{ object.obs|linebreaks }}</td>

            </tr>

            <tr>
                <th class="text-right">Distancia eje Y</th>
                <td>{{ object.latitud }}</td>

            </tr>

            <tr>
                <th class="text-right">Distancia eje X</th>
                <td>{{ object.logitud }}</td>

            </tr>

            <tr>
                <th class="text-right">Posee material de herbario</th>
                <td>{{ object.has_herbarium|yesno:"sí,no" }}</td>

            </tr>

            {% if object.herbarium_info %}

            <tr>
                <th class="text-right">Información material de herbario</th>
                <td>{{ object.herbarium_info }}</td>

            </tr>

            {% endif %}

            <tr>
                <th class="text-right">fecha y hora de registro</th>
                <td>{{ object.created_at }}</td>

            </tr>
            </tbody>
        </table>

    </div>

    <div class="col-sm-8">
        <div id="map-detail">
            {% leaflet_map "map-detail" %}
        </div>
    </div>
</div>
<div class="row">
    <div class="jumbotron">
    <div class="col-fluid">
        <h2>Lista mediciones</h2>

    <table class='table table-striped'>
        <thead>
        <tr>
            <th>ID</th>
            <th>Individuo</th>
            <th>DAB</th>
            <th>DAP</th>
            <th>Altura</th>
        </tr>
        </thead>

        {% for measure in measurement_list %}
        <tr>
            <td>
                <a href="{{ measure.get_absolute_url }}">{{ measure }}</a>
            </td>
            <td>{{ measure.tree.specie }}</td>
            <td>{{ measure.dab }}</td>
            <td>{{ measure.dap }}</td>
            <td>{{ measure.tree_height }}</td>

        </tr>
        {% endfor %}
    </table>
    </div>
    </div>
</div>
<script>
    var dataurl = '{% url "imibio_tree_ecological_data:plot_detail_geojson" pk=object.field.parcel_id.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
                 map.fitBounds(layer.getBounds(), { maxZoom: 15 });
            }}).addTo(map);
          });
      });

      var TreeDataURL = '{% url "imibio_tree_ecological_data:Tree_detail_geojson" pk=object.pk %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        fetch(TreeDataURL)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });


</script>


{% endblock content %}

sysimibio/imibio_tree_ecological_data/templates/imibio_tree_ecological_data/tree_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="jumbotron">
    <div class="container">
          <a role="button" class="btn btn-success btn-lg" href="{% url 'imibio_tree_ecological_data:tree_list' %}">
                <span class="align-middle">Volver</span>
            </a>
        <h2>Registro de indivíduos arbóreos</h2>
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger" role="alert">
            <p>{{ message }}</p>
        </div>
        {% else %}
        <div class="alert alert-success" role="alert">
            <p>{{ message }}</p>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        <div class="accordion" id="accordionExample">
            <form method="POST" action="." class="post-form">
                {% csrf_token %}

                 {% crispy form %}


            </form>
        </div>
    </div>
</div>

{% endblock %}