sysimibio/bioblitz/urls.py
from django.urls import path

from sysimibio.bioblitz.views import (
    register_bioblitz_project,
    register_bioblitz_occurrences,
    list_bioblitz_occurrences,
    list_bioblitz_projects,
    bioblitz_occurrence_detail,
    project_detail,
    project_stats,
    proj_occs_geojson,
    bioblitz_events_stats,
    bioblitz_events_geojson,
    observation_detail_geojson,
)

app_name = "bioblitz"


urlpatterns = [
    path("", register_bioblitz_project, name="register_bioblitz_project"),
    path("project_list", list_bioblitz_projects, name="list_bioblitz_projects"),
    path("bioblitz_events_stats", bioblitz_events_stats, name="bioblitz_events_stats"),
    path("project_detail/<int:pk>/", project_detail, name="project_detail"),
    path(
        "get_occurrences/<int:project_id>/",
        register_bioblitz_occurrences,
        name="get_occurrences",
    ),
    path(
        "get_project_occurrence_geojson/<int:pk>/",
        proj_occs_geojson,
        name="project_occurrence_geojson",
    ),
    path(
        "bioblitz_events_occurrences_geojson/",
        bioblitz_events_geojson,
        name="bioblitz_events_geojson",
    ),
    path(
        "bioblitz_occurrence_detail_geojson/<int:pk>/",
        observation_detail_geojson,
        name="bioblitz_occurrence_geojson",
    ),
    path(
        "list_occurrences/<int:pk>/", list_bioblitz_occurrences, name="list_occurrences"
    ),
    path(
        "occurrence_detail/<int:pk>/",
        bioblitz_occurrence_detail,
        name="occurrence_detail",
    ),
    path("project_stats/<int:pk>/", project_stats, name="project_stats"),
]

sysimibio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sysimibio.core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sysimibio.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", home, name="home"),
    path(
        "imibio_occurrences/", include("sysimibio.imibio_occurrences.urls")
    ),  # todo cambiar a ingles
    path(
        "imibio_tree_ecological_data/",
        include("sysimibio.imibio_tree_ecological_data.urls"),
    ),  # todo cambiar a ingles
    path("bioblitz/", include("sysimibio.bioblitz.urls")),
    path("bibliography/", include("sysimibio.bibliography.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/bioblitz/models.py
from django.db import models
from django.urls import reverse_lazy
from djgeojson.fields import PointField

# Create your models here.


class BioblitzProject(models.Model):
    iconURL = models.URLField(verbose_name="URL del icono del proyecto", blank=True)
    description = models.TextField(verbose_name="Descripción del proyecto", blank=True)
    created_at = models.DateTimeField(verbose_name="Fecha de creacción")
    title = models.CharField(verbose_name="Título del proyecto", max_length=200)
    project_id = models.IntegerField(verbose_name="Id del proyecto", unique=True)
    project_slug = models.CharField(
        verbose_name="Nombre del proyecto",
        max_length=250,
        help_text="(Nombre sin espacio. Con guión)",
    )
    place_id = models.IntegerField(verbose_name="Id del local", unique=True)
    project_type = models.CharField(verbose_name="Tipo de proyecto", max_length=100)
    manager_id = models.IntegerField(verbose_name="Id del administrador", unique=True)
    manager_login = models.CharField(
        verbose_name="Login del administrador", max_length=200
    )
    manager_name = models.CharField(
        verbose_name="Nombre del administrador", max_length=200
    )

    def __str__(self):
        return f"{self.title} {self.manager_name} {self.project_id}"

    def get_absolute_url(self):
        return reverse_lazy("bioblitz:project_detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Proyecto de BioBlitz"
        verbose_name_plural = "Proyecto de BioBlitz"


class BioblitzOccurrence(models.Model):  # todo work with sounds?
    project_id = models.ForeignKey("BioBlitzProject", on_delete=models.CASCADE)
    obs_id = models.IntegerField("ID de la observación")
    quality_grade = models.CharField("Calidad de ranking", max_length=50)
    created_at = models.DateTimeField("Fecha de la observación")
    uri = models.URLField("URL de la observación")
    # taxon
    taxon_name = models.CharField(
        "Nombre cientifico de la especie", max_length=300, blank=True, default=""
    )
    taxon_rank = models.CharField(
        "Ranking taxonomico", max_length=50, blank=True, default=""
    )
    iconic_taxon_name = models.CharField("Grupo", max_length=50, blank=True, default="")
    endemic = models.BooleanField("Especie endémica?", default=False)
    threatened = models.BooleanField("Especie amenazada?", default=False)
    introduced = models.BooleanField("Especie introducida?", default=False)
    native = models.BooleanField("Especie nativa?", default=False)
    # geo
    geom = PointField(null=True)
    # User
    user_id = models.IntegerField("ID del observador")
    user_login = models.CharField("Login del observador", max_length=50)
    user_name = models.CharField("Nombre del observador", max_length=100, null=True)

    def __str__(self):
        return f"{self.taxon_name} - {self.project_id}"

    def get_absolute_url(self):
        return reverse_lazy("bioblitz:occurrence_detail", kwargs={"pk": self.pk})

    def get_project_absolute_url(self):
        return reverse_lazy(
            "bioblitz:project_detail", kwargs={"pk": self.project_id.pk}
        )

    @property
    def popup_content(self):  # todo Me parece que lo importante es poner alguna foto
        popup = "<strong><span>Nombre científico: </span>{}</strong><br>".format(
            self.taxon_name
        )
        popup += "<span>Altura: </span>{}<br>".format(self.iconic_taxon_name)
        popup += (
            f"<span>Especie amenazada: </span>{'sí' if self.threatened else 'no'}<br>"
        )
        popup += f"<span>Usuário: </span>{self.user_login}<br>"
        popup += f"<span><a href={self.get_project_absolute_url()}>Detalles del proyecto</a></strong><br>"
        popup += f"<span><a href={self.get_absolute_url()}>Detalles de la occurrencia</a></strong><br>"
        return popup

    class Meta:
        verbose_name = "Especie observada"
        verbose_name_plural = "Especies observadas"

sysimibio/bioblitz/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from sysimibio.bioblitz.models import BioblitzProject


class BioblitzModelForm(ModelForm):
    class Meta:
        model = BioblitzProject
        fields = ["project_slug"]

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get("project_slug") and not cleaned_data.get("project_id"):
            raise ValidationError("Informar nombre del proyecto o id")

sysimibio/bioblitz/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, resolve_url as r
from djgeojson.views import GeoJSONLayerView
from pyinaturalist.node_api import get_projects, get_observations

# Create your views here.
from sysimibio.bioblitz.forms import BioblitzModelForm
from sysimibio.bioblitz.models import BioblitzProject, BioblitzOccurrence


@login_required
def register_bioblitz_project(request):
    if request.method == "POST":
        form = BioblitzModelForm(request.POST)

        if not form.is_valid():
            messages.error(request, "Formulário con error: revise todos los campos")
            return render(
                request, "bioblitz/project_registration_form.html", {"form": form}
            )

        elif form.cleaned_data.get("project_slug") in [
            val["project_slug"]
            for val in list(BioblitzProject.objects.all().values("project_slug"))
        ]:
            messages.error(request, "Proyecto ya cargado al sistema")
            return render(
                request, "bioblitz/project_registration_form.html", {"form": form}
            )

        else:
            bioblitz_project_data = get_projects(
                q=form.cleaned_data.get("project_slug"), member_id=1626810
            )
            if bioblitz_project_data.get("total_results") == 0:
                messages.error(
                    request, "Proyecto no encontrado. confirmar nombre del proyecto"
                )
                return render(
                    request, "bioblitz/project_registration_form.html", {"form": form}
                )

            project = BioblitzProject.objects.create(
                iconURL=bioblitz_project_data.get("results")[0].get("icon"),
                description=bioblitz_project_data.get("results")[0].get("description"),
                created_at=bioblitz_project_data.get("results")[0].get("created_at"),
                title=bioblitz_project_data.get("results")[0].get("title"),
                project_id=bioblitz_project_data.get("results")[0].get("id"),
                project_slug=bioblitz_project_data.get("results")[0].get("slug"),
                place_id=bioblitz_project_data.get("results")[0].get("place_id"),
                project_type=bioblitz_project_data.get("results")[0].get(
                    "project_type"
                ),
                manager_id=bioblitz_project_data.get("results")[0]
                .get("admins")[0]
                .get("user")
                .get("id"),
                manager_login=bioblitz_project_data.get("results")[0]
                .get("admins")[0]
                .get("user")
                .get("login"),
                manager_name=bioblitz_project_data.get("results")[0]
                .get("admins")[0]
                .get("user")
                .get("name"),
            )
            messages.success(request, "Proyecto registrado con exito")

            return HttpResponseRedirect(r("bioblitz:project_detail", project.pk))

    return render(
        request,
        "bioblitz/project_registration_form.html",
        {"form": BioblitzModelForm()},
    )


@login_required
def list_bioblitz_projects(request):
    ptojects = BioblitzProject.objects.all()
    return render(request, "bioblitz/projects_list.html", {"projects": ptojects})


@login_required
def project_detail(request, pk):
    try:
        project = BioblitzProject.objects.get(pk=pk)
        project_occurrences = BioblitzOccurrence.objects.filter(project_id__pk=pk)
        if not project_occurrences:
            messages.info(request, "Proyecto sin occurrencias")
        context = {"project": project, "occurences": project_occurrences}
    except BioblitzProject.DoesNotExist:
        raise Http404

    return render(request, "bioblitz/project_detail.html", context)


@login_required
def register_bioblitz_occurrences(request, project_id):
    try:
        project = BioblitzProject.objects.get(project_id=project_id)
        observations = get_observations(
            project_id=project_id, page="all"
        )  # todo consider user_agent https://pyinaturalist.readthedocs.io/en/v0.13.0/general_usage.html#user-agent
        total_obs = len(observations.get("results"))
        for obs in observations.get(
            "results"
        ):  # todo get a better way to map dict variables
            # print(obs.get("id"))
            project_id = project
            obs_id = obs.get("id")
            quality_grade = obs.get("quality_grade")
            created_at = obs.get("created_at")
            uri = obs.get("uri")
            geom = obs.get("geojson", "")
            # taxon
            if obs.get("taxon"):
                name = obs.get("taxon").get("name")
                rank = obs.get("taxon").get("rank")
                iconic_taxon_name = obs.get("taxon").get("iconic_taxon_name", "")
                endemic = obs.get("taxon").get("endemic")
                threatened = obs.get("taxon").get("threatened")
                introduced = obs.get("taxon").get("introduced")
                native = obs.get("taxon").get("native")
            else:
                name = ""
                rank = ""
                iconic_taxon_name = ""
                endemic = False
                threatened = False
                introduced = False
                native = False

            # user
            user_login = obs.get("user").get("login")
            user_name = obs.get("user").get("name")
            user_id = obs.get("user").get("id")

            BioblitzOccurrence.objects.create(
                project_id=project_id,
                obs_id=obs_id,
                quality_grade=quality_grade,
                created_at=created_at,
                uri=uri,
                taxon_name=name,
                taxon_rank=rank,
                iconic_taxon_name=iconic_taxon_name,
                endemic=endemic,
                threatened=threatened,
                introduced=introduced,
                native=native,
                geom=geom,
                user_id=user_id,
                user_name=user_name,
                user_login=user_login,
            )

        messages.success(request, f"{total_obs} observaciones cargadas con exito")
        return HttpResponseRedirect(r("bioblitz:list_occurrences", project.pk))

    except BioblitzProject.DoesNotExist:
        raise Http404


@login_required
def list_bioblitz_occurrences(request, pk):
    observations = BioblitzOccurrence.objects.filter(project_id__pk=pk)
    context = {"observations": observations, "project_pk": pk}
    return render(request, "bioblitz/occurrences_list.html", context)


@login_required
def bioblitz_occurrence_detail(request, pk):
    try:
        observation = BioblitzOccurrence.objects.get(pk=pk)
    except BioblitzProject.DoesNotExist:
        raise Http404
    return render(
        request, "bioblitz/occurrence_detail.html", {"observation": observation}
    )


@login_required
def project_stats(request, pk):
    # Observations
    labelsObsQGrade = []
    dataObsQGrade = []
    labelsObsRank = []
    dataObsRank = []
    labelsObsITName = []
    dataObsITName = []
    labelsObsUser = []
    dataObsUser = []

    # Species
    labelsSppQGrade = []
    dataSppQGrade = []
    labelsSppRank = []
    dataSppRank = []
    labelsSppITName = []
    dataSppITName = []
    labelsSppUser = []
    dataSppUser = []

    # return object
    data = dict()
    labels = dict()

    # Observation
    # quality grade
    querysetGrade = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)
        .values("quality_grade")
        .annotate(Count("obs_id"))
        .order_by("-obs_id__count")[:10]
    )
    for QGrade in querysetGrade:
        labelsObsQGrade.append(QGrade.get("quality_grade"))
        dataObsQGrade.append(QGrade.get("obs_id__count"))

    data["ObsQGrade"] = dataObsQGrade
    labels["ObsQGrade"] = labelsObsQGrade

    # Rank
    querysetRank = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)
        .values("taxon_rank")
        .annotate(Count("obs_id"))
        .order_by("-obs_id__count")[:10]
    )
    for rank in querysetRank:
        labelsObsRank.append(rank.get("taxon_rank"))
        dataObsRank.append(rank.get("obs_id__count"))

    data["ObsRank"] = dataObsRank
    labels["ObsRank"] = labelsObsRank

    # ITName
    querysetITName = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)
        .values("iconic_taxon_name")
        .annotate(Count("obs_id"))
        .order_by("-obs_id__count")[:10]
    )
    for ITName in querysetITName:
        labelsObsITName.append(ITName.get("iconic_taxon_name"))
        dataObsITName.append(ITName.get("obs_id__count"))

    data["ObsITName"] = dataObsITName
    labels["ObsITName"] = labelsObsITName

    # User_id
    querysetUser = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)
        .values("user_login")
        .annotate(Count("obs_id"))
        .order_by("-obs_id__count")[:10]
    )
    for user in querysetUser:
        labelsObsUser.append(user.get("user_login"))
        dataObsUser.append(user.get("obs_id__count"))

    data["ObsUser"] = dataObsUser
    labels["ObsUser"] = labelsObsUser

    # species
    # quality grade
    querysetGradeSpp = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)
        .values("quality_grade")
        .annotate(Count("taxon_name", distinct=True))
        .order_by("-taxon_name__count")[:10]
    )
    for QGradeSpp in querysetGradeSpp:
        labelsSppQGrade.append(QGradeSpp.get("quality_grade"))
        dataSppQGrade.append(QGradeSpp.get("taxon_name__count"))

    data["SppQGrade"] = dataSppQGrade
    labels["SppQGrade"] = labelsSppQGrade

    # Rank
    querysetRankSpp = (
        BioblitzOccurrence.objects.filter(project_id__pk=pk)

sysimibio/bioblitz/templates/bioblitz/bioblitz_detail.html
{% extends "base.html" %}

{% block content %}

{% if messages %}
            {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        <p>{{ message }}</p>
                    </div>
            {% endfor %}
{% endif %}

<br>
<a  role="button" class="btn navbar-btn btn-success" href="{% url 'home' %}">Voltar</a>
<br>

<h1>Detalles del Bioblitz: {{ project.title }}</h1>
<strong>id: {{ project.pk }}</strong>
<div class="row">
<div class="col-sm-4">
    <table class = "table table-user-information">
        <tbody>
        <tr>
            <th class="text-right">Nombre del proyecto</th>
            <td>{{ project.title }}</td>
        </tr>
        <tr>

            <th class="text-right">ID del proyecto</th>
            <td>{{ project.project_id }}</td>
        </tr>

            <th class="text-right">Fecha de creación</th>
            <td>{{ project.created_at }}</td>
        </tr>

            <th class="text-right">Descripción</th>
            <td>{{ project.description }}</td>
        </tr>

            <th class="text-right">Tipo de proyecto</th>
            <td>{{ project.project_type }}</td>
        </tr>

            <th class="text-right">Administrador</th>
            <td>{{ project.manager_name }}</td>
        </tr>

        </tbody>
    </table>
</div>
</div>
<br>
<a  role="button" class="btn navbar-btn btn-warning" href="{% url 'bioblitz:get_occurrences' pk=project.project_id %}">Get occs</a>
<a  role="button" class="btn navbar-btn btn-success" href="{% url 'bioblitz:list_occurrences' %}">View occs</a>
<a  role="button" class="btn navbar-btn btn-dark" href="{% url 'bioblitz:pie-chart' %}">View stats</a>
<br>
{% endblock content %}

sysimibio/bioblitz/templates/bioblitz/bioblitz_events_stats.html
{% extends 'base.html' %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
    {% leaflet_js %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }
</style>
<div class="row">
        <a  role="button" class="btn navbar-btn btn-success btn-lg" href="{% url 'bioblitz:list_bioblitz_projects' %}">
            <span class="align-middle">Volver</span></a>
        &nbsp; <h1>Estadísticas de los proyectos de bioblitz</h1>
</div>
<div class = "jumbotron">

    <div class = "container-fluid">
        <div class="accordion" id="accordionExample">
            <div class="card ">
                <div class="card-header" id="collapseThree">
                    <h3 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                            Distribución observaciones
                        </button>
                    </h3>
                </div>
                    <div id="collapseThree" class="collapse show" aria-labelledby="collapseThree" data-parent="#accordionExample">
                        <div class="card-body" style="height: 30rem;">
                            <div id="map-detail">
                                {% leaflet_map "map-detail" %}
                            </div>
                        </div>
                    </div>
            </div>
            <div class="card ">
                <div class="card-header" id="headingOne">
                    <h3 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Estadísticas
                        </button>
                    </h3>
                </div>
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="row row-cols-2">

                                  <div class="col">
                                      <div class="jumbotron">
                                        <h3>Total de observaciones</h3>
                                        <div id="container">
                                          <canvas id="ObsAmount"></canvas>
                                        </div>
                                      </div>
                                  </div>

                                  <div class="col">
                                      <div class="jumbotron">
                                        <h3>Total de especies observadas</h3>
                                        <div id="container">
                                          <canvas id="SppAmount"></canvas>
                                        </div>
                                      </div>
                                  </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>


<script>

<!--Charts-->
    var configObsAmount = {
      type: 'bar',
      data: {
        datasets: [{
          data: {{ data.ObsAmount|safe }},
          backgroundColor: [
            '#e41a1c', '#377eb8', '#4daf4a', '#984ea3', '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999'
          ],
          label: 'group'
        }],
        labels: {{ labels.ObsAmount|safe }}
      },
      options: {
        responsive: true
      }
    };

   var configSppAmount = {
      type: 'bar',
      data: {
        datasets: [{
          data: {{ data.SppAmount|safe }},
          backgroundColor: [
            '#e41a1c', '#377eb8', '#4daf4a', '#984ea3', '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999'
          ],
          label: 'Group'
        }],
        labels: {{ labels.SppAmount|safe }}
      },
      options: {
        responsive: true
      }
    };


    window.onload = function() {

      var ctxObsAmount = document.getElementById('ObsAmount').getContext('2d');
      window.ObsAmount = new Chart(ctxObsAmount, configObsAmount);

      var ctxSppAmount = document.getElementById('SppAmount').getContext('2d');
      window.SppAmount = new Chart(ctxSppAmount, configSppAmount);
    };

<!--MAP-->
      var dataurl = '{% url "bioblitz:bioblitz_events_geojson" %}';

      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });

  </script>

{% endblock %}

sysimibio/bioblitz/templates/bioblitz/occurrence_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
    {% leaflet_js %}
{% endblock %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }
</style>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            <p>{{ message }}</p>
        </div>
    {% endfor %}
{% endif %}

<br>
<a  role="button" class="btn navbar-btn btn-success" href="{% url 'bioblitz:list_occurrences' pk=observation.project_id.pk %}">Volver</a>
<br>

<h1>Detalles de la observación: {{ observation.taxon_name }}</h1>
<strong>id: {{ observation.pk }}</strong>
<div class="row">
<div class="col-sm-4">
    <table class = "table table-user-information">
        <tbody>
        <tr>
            <th class="text-right">proj_id</th>
            <td>{{ observation.project_id }}</td>
        </tr>
        <tr>
            <th class="text-right">Nombre de la especie</th>
            <td><a href="{{ observation.uri }}">{{ observation.taxon_name }}</a></td>
        </tr>
        <tr>
            <th class="text-right">Calidad</th>
            <td>{{ observation.quality_grade }}</td>
        </tr>
        <tr>
            <th class="text-right">Fecha de creación</th>
            <td>{{ observation.created_at }}</td>
        </tr>
        <tr>
            <th class="text-right">Ranking taxonómico</th>
            <td>{{ observation.rank }}</td>
        </tr>
        <tr>
            <th class="text-right">grupo</th>
            <td>{{ observation.iconic_taxon_name }}</td>
        </tr>
        <tr>
            <th class="text-right">endemic</th>
            <td>{{ observation.endemic|yesno:'Sí,No' }}</td>
        </tr>
        <tr>
            <th class="text-right">threatened</th>
            <td>{{ observation.threatened|yesno:'Sí,No' }}</td>
        </tr>
        <tr>
            <th class="text-right">introduced</th>
            <td>{{ observation.introduced|yesno:'Sí,No' }}</td>
        </tr>
        <tr>
            <th class="text-right">native</th>
            <td>{{ observation.native|yesno:'Sí,No' }}</td>
        </tr>
        </tbody>
    </table>
</div>
<div class="col-sm-8">
    <div id="map-detail">
        {% leaflet_map "map-detail" %}
    </div>
</div>

</div>
<a  role="button" class="btn navbar-btn btn-warning" href="{{ observation.uri }}">Ir a INaturalist</a>

    <script>
      var dataurl = '{% url "bioblitz:bioblitz_occurrence_geojson" pk=observation.pk %}';

      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });

    </script>


{% endblock content %}

sysimibio/bioblitz/templates/bioblitz/project_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
    {% leaflet_js %}
{% endblock %}

{% block css %}
    {% leaflet_css %}
{% endblock %}

{% block content %}
<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }
</style>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            <p>{{ message }}</p>
        </div>
    {% endfor %}
{% endif %}


<br>
<div class="row">
    <a  role="button" class="btn btn-success btn-lg" href="{% url 'bioblitz:list_bioblitz_projects' %}">
        <span class="align-middle">Volver</span>
    </a>
    &nbsp; <h2>Detalles del Bioblitz: {{ project.title }}</h2>
</div>
<div class="row">
<div class="col-sm-4">
    <table class = "table table-user-information">
        <tbody>
        <tr>
            <th class="text-right">Nombre del proyecto</th>
            <td>{{ project.title }}</td>
        </tr>
        <tr>

            <th class="text-right">ID del proyecto</th>
            <td>{{ project.project_id }}</td>
        </tr>

            <th class="text-right">Fecha de creación</th>
            <td>{{ project.created_at }}</td>
        </tr>

            <th class="text-right">Descripción</th>
            <td>{{ project.description }}</td>
        </tr>

            <th class="text-right">Tipo de proyecto</th>
            <td>{{ project.project_type }}</td>
        </tr>

            <th class="text-right">Administrador</th>
            <td>{{ project.manager_name }}</td>
        </tr>

        </tbody>
    </table>
    {% if not occurences %}
        <a  role="button" class="btn navbar-btn btn-warning" href="{% url 'bioblitz:get_occurrences' project_id=project.project_id %}">Descargar observaciones</a>
    {% endif %}
    {% if occurences %}
        <a  role="button" class="btn navbar-btn btn-success" href="{% url 'bioblitz:list_occurrences' pk=project.pk %}">Listar observaciones</a>
        <a  role="button" class="btn navbar-btn btn-dark" href="{% url 'bioblitz:project_stats' pk=project.pk %}">Estadísticas</a>
    {% endif %}
    </div>

<div class="col-sm-8">
    <div id="map-detail">
        {% leaflet_map "map-detail" %}
    </div>
</div>
    <script>
      var dataurl = '{% url "bioblitz:project_occurrence_geojson" pk=project.pk %}';

      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });

    </script>


{% endblock content %}