sysimibio/bibliography/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from sysimibio.bibliography.views import (
    PublicationList,
    PublicationDetail,
    PublicationUpdateView,
    PublicationCreateView,
    SpeciesListUpdateView,
    SpeciesListCreateView,
    OccurrenceListCreateView,
    OccurrenceListUpdateView,
    PublicationOccurrenceListGeoJsonView,
    AllPublicationOccurrenceListGeoJsonView,
    AllPublicationOccurrencesMap,
    ListAllPublicationOccurrences,
    ListAllPublicationSpecies,
)

app_name = "bibliography"

urlpatterns = [
    path("new/", PublicationCreateView, name="publication_new"),
    path("detail/<int:pk>/", PublicationDetail, name="publication_detail"),
    path("list/", PublicationList, name="publication_list"),
    path("edit/<int:pk>/", PublicationUpdateView, name="publication_edit"),
    path("new/specieslist/<int:pk>/", SpeciesListCreateView, name="specieslist_new"),
    path("edit/specieslist/<int:pk>/", SpeciesListUpdateView, name="specieslist_edit"),
    path(
        "new/occurrenceslist/<int:pk>/",
        OccurrenceListCreateView,
        name="occurrenceslist_new",
    ),
    path(
        "edit/occurrenceslist/<int:pk>/",
        OccurrenceListUpdateView,
        name="occurrenceslist_edit",
    ),
    path(
        "geojson/occurrenceslist/<int:pk>/",
        PublicationOccurrenceListGeoJsonView,
        name="publication_occurrenceslist_geojson",
    ),
    path(
        "geojson/occurrenceslist/",
        AllPublicationOccurrenceListGeoJsonView,
        name="all_publication_occurrenceslist_geojson",
    ),
    path(
        "map/occurrenceslist/",
        AllPublicationOccurrencesMap,
        name="map_all_publication_occurrenceslist",
    ),
    path(
        "list/occurrenceslist/", ListAllPublicationOccurrences, name="occurrenceslist"
    ),
    path("list/specieslist/", ListAllPublicationSpecies, name="specieslist"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/bioblitz/urls.py
from django.urls import path

from sysimibio.bioblitz.views import (
    register_bioblitz_project,
    register_bioblitz_occurrences,
    list_bioblitz_occurrences,
    list_bioblitz_projects,
    bioblitz_occurrence_detail,
    project_detail,
    project_stats,
    proj_occs_geojson,
    bioblitz_events_stats,
    bioblitz_events_geojson,
    observation_detail_geojson,
)

app_name = "bioblitz"


urlpatterns = [
    path("", register_bioblitz_project, name="register_bioblitz_project"),
    path("project_list", list_bioblitz_projects, name="list_bioblitz_projects"),
    path("bioblitz_events_stats", bioblitz_events_stats, name="bioblitz_events_stats"),
    path("project_detail/<int:pk>/", project_detail, name="project_detail"),
    path(
        "get_occurrences/<int:project_id>/",
        register_bioblitz_occurrences,
        name="get_occurrences",
    ),
    path(
        "get_project_occurrence_geojson/<int:pk>/",
        proj_occs_geojson,
        name="project_occurrence_geojson",
    ),
    path(
        "bioblitz_events_occurrences_geojson/",
        bioblitz_events_geojson,
        name="bioblitz_events_geojson",
    ),
    path(
        "bioblitz_occurrence_detail_geojson/<int:pk>/",
        observation_detail_geojson,
        name="bioblitz_occurrence_geojson",
    ),
    path(
        "list_occurrences/<int:pk>/", list_bioblitz_occurrences, name="list_occurrences"
    ),
    path(
        "occurrence_detail/<int:pk>/",
        bioblitz_occurrence_detail,
        name="occurrence_detail",
    ),
    path("project_stats/<int:pk>/", project_stats, name="project_stats"),
]

sysimibio/imibio_occurrences/urls.py
from django.urls import path

from sysimibio.imibio_occurrences.views import registration, detail

app_name = "imibio_occurrences"

urlpatterns = [
    path("", registration, name="new"),
    path("<int:pk>/", detail, name="detail"),
]

sysimibio/imibio_tree_ecological_data/urls.py
from django.urls import path
from django.views.generic import TemplateView

from sysimibio.imibio_tree_ecological_data.views import (
    trees_geojson,
    PlotListView,
    PlotDetailView,
    PlotDetailGeoJson,
    PlotCreateView,
    PlotEditView,
    FieldWorkListView,
    FieldWorkDetailView,
    FieldWorkEditView,
    FieldWorkCreateView,
    TreeCreateView,
    TreeDetailView,
    TreeDetailGeoJson,
    TreeEditView,
    TreeListView,
    TreeMeasurementCreateView,
    TreeMeasurementDetailView,
    TreeMeasurementEditView,
    TreeMeasurementListView,
    PlotDetailTreesGeoJson,
    FieldWorkDetailTreesGeoJson,
)

app_name = "imibio_tree_ecological_data"

urlpatterns = [
    # plot
    path("create/plot/", PlotCreateView, name="plot_create"),
    path("edit/plot/<int:pk>/", PlotEditView, name="plot_edit"),
    path("list/plot/", PlotListView, name="plot_list"),
    path("detail/plot/<int:pk>/", PlotDetailView, name="plot_detail"),
    path("geojson/plot/<int:pk>/", PlotDetailGeoJson, name="plot_detail_geojson"),
    path(
        "geojson/plot/<int:pk>/trees",
        PlotDetailTreesGeoJson,
        name="trees_plot_detail_geojson",
    ),
    # field work
    path("create/field/", FieldWorkCreateView, name="field_create"),
    path("edit/field/<int:pk>/", FieldWorkEditView, name="field_edit"),
    path("list/field/", FieldWorkListView, name="field_list"),
    path("detail/field/<int:pk>/", FieldWorkDetailView, name="field_detail"),
    path(
        "geojson/field/<int:pk>/trees",
        FieldWorkDetailTreesGeoJson,
        name="trees_field_detail_geojson",
    ),
    # tree
    path("create/tree/", TreeCreateView, name="tree_create"),
    path("edit/tree/<int:pk>/", TreeEditView, name="tree_edit"),
    path("list/tree/", TreeListView, name="tree_list"),
    path("detail/tree/<int:pk>/", TreeDetailView, name="tree_detail"),
    path("geojson/tree/<int:pk>/", TreeDetailGeoJson, name="Tree_detail_geojson"),
    # tree measurement
    path(
        "create/tree/measurement/",
        TreeMeasurementCreateView,
        name="tree_measurement_create",
    ),
    path(
        "edit/tree/measurement/<int:pk>/",
        TreeMeasurementEditView,
        name="tree_measurement_edit",
    ),
    path(
        "list/tree/measurement/", TreeMeasurementListView, name="tree_measurement_list"
    ),
    path(
        "detail/tree/measurement/<int:pk>/",
        TreeMeasurementDetailView,
        name="tree_measurement_detail",
    ),
    # general
    path("geojson/", trees_geojson, name="data"),
    path("map/", TemplateView.as_view(template_name="tree_map.html"), name="map"),
]

sysimibio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sysimibio.core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sysimibio.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", home, name="home"),
    path(
        "imibio_occurrences/", include("sysimibio.imibio_occurrences.urls")
    ),  # todo cambiar a ingles
    path(
        "imibio_tree_ecological_data/",
        include("sysimibio.imibio_tree_ecological_data.urls"),
    ),  # todo cambiar a ingles
    path("bioblitz/", include("sysimibio.bioblitz.urls")),
    path("bibliography/", include("sysimibio.bibliography.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "index.html")

sysimibio/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <span class="navbar-brand disabled">
        <img src="http://imibio.misiones.gob.ar/logoblancochico.png" style="height: 40px; width: auto;" alt="">
    </span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <li class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}"> Início <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Datos SNDB</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item disabled" href="">
                        <i class="fa fa-pagelines"></i> Lista ocurrencias</a>
                    <a class="dropdown-item disabled" href="">
                        <i class="fa fa-globe"></i> Mapa ocurrencias</a>
                    <a class="dropdown-item disabled" href="#">
                        <i class="fa fa-bar-chart"></i> Estadísticas</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown02" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Datos IMiBio</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <!--<a class="dropdown-item" href="<{% url 'imibio_occurrences:new' %}"> Agregar ocurencia</a>
                    <a class="dropdown-item disabled" href="">Mapa Ocurrencias</a>
                    <a class="dropdown-item disabled" href="">Estadísticas</a>-->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="bioblitz" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Datos Bioblitz</a>
                <div class="dropdown-menu" aria-labelledby="bioblitz">
                    <a class="dropdown-item" href="{% url 'bioblitz:register_bioblitz_project' %}">
                        <i class="fa fa-plus"></i> Registrar proyecto</a>
                    <a class="dropdown-item" href="{% url 'bioblitz:list_bioblitz_projects' %}">
                        <i class="fa fa-book"></i> Lista de proyectos de Bioblitz</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bibliografia" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"> Bibliografía</a>
                <div class="dropdown-menu" aria-labelledby="bibliografia">
                    <a class="dropdown-item " href="{% url 'bibliography:publication_new' %}">
                        <i class="fa fa-plus"></i> Agregar Bibliografía</a>
                    <a class="dropdown-item " href="{% url 'bibliography:publication_list' %}">
                        <i class="fa fa-book"></i> Lista de Bibliografías</a>
                    <a class="dropdown-item " href="{% url 'bibliography:specieslist' %}">
                        <i class="fa fa-list"></i> Lista de especies</a>
                    <a class="dropdown-item " href="{% url 'bibliography:occurrenceslist' %}">
                        <i class="fa fa-list-ul"></i> Lista de ocurrencias</a>
                    <a class="dropdown-item " href="{% url 'bibliography:map_all_publication_occurrenceslist' %}">
                        <i class="fa fa-map-marker"></i> Mapa Ocurrencias</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown_ppi" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Parcelas permanentes</a>
                <div class="dropdown-menu" aria-labelledby="dropdown_ppi">
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:plot_create' %}">
                        <i class="fa fa"></i> Registrar nueva Parcela</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:plot_list' %}">
                        <i class="fa fa"></i> Lista de Parcelas</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:field_create' %}">
                        <i class="fa fa"></i> Registrar nuevo campo</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:field_list' %}">
                        <i class="fa fa"></i> Lista de campos</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:tree_create' %}">
                        <i class="fa fa"></i> Registrar individuos arbóreos</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:tree_list' %}">
                        <i class="fa fa"></i> Lista de individuos arbóreos</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:tree_measurement_create' %}">
                        <i class="fa fa"></i> Registrar medición de árboles</a>
                    <a class="dropdown-item" href="{% url 'imibio_tree_ecological_data:tree_measurement_list' %}">
                        <i class="fa fa"></i> Lista de mediciones de árboles</a>
                </div>
            </li>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </for\m>-->
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}

            {% if user.is_superuser %}
            <li class="nav-item">
                <a role="button" class="btn btn-warning" href="{% url 'signup' %}"> Crear usuario </a>
            </li>
            <li class="nav-item">' '</li>

            {% endif %}

            <li class="nav-item">
                <a role="button" class="btn btn-danger" href="{% url 'logout' %}">
                    <span></span><span class="fa fa-sign-in"></span> Salir </a>
            </li>


            {% else %}
            <li class="nav-item">
                <a role="button" class="btn navbar-btn btn-success" href="{% url 'login' %}">
                    <span class="fa fa-user"></span> Login </a>
            </li>
            {% endif %}
        </ul>
    </li>

</nav>