sysimibio/bibliography/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from sysimibio.bibliography.views import (
    PublicationList,
    PublicationDetail,
    PublicationUpdateView,
    PublicationCreateView,
    SpeciesListUpdateView,
    SpeciesListCreateView,
    OccurrenceListCreateView,
    OccurrenceListUpdateView,
    PublicationOccurrenceListGeoJsonView,
    AllPublicationOccurrenceListGeoJsonView,
    AllPublicationOccurrencesMap,
    ListAllPublicationOccurrences,
    ListAllPublicationSpecies,
)

app_name = "bibliography"

urlpatterns = [
    path("new/", PublicationCreateView, name="publication_new"),
    path("detail/<int:pk>/", PublicationDetail, name="publication_detail"),
    path("list/", PublicationList, name="publication_list"),
    path("edit/<int:pk>/", PublicationUpdateView, name="publication_edit"),
    path("new/specieslist/<int:pk>/", SpeciesListCreateView, name="specieslist_new"),
    path("edit/specieslist/<int:pk>/", SpeciesListUpdateView, name="specieslist_edit"),
    path(
        "new/occurrenceslist/<int:pk>/",
        OccurrenceListCreateView,
        name="occurrenceslist_new",
    ),
    path(
        "edit/occurrenceslist/<int:pk>/",
        OccurrenceListUpdateView,
        name="occurrenceslist_edit",
    ),
    path(
        "geojson/occurrenceslist/<int:pk>/",
        PublicationOccurrenceListGeoJsonView,
        name="publication_occurrenceslist_geojson",
    ),
    path(
        "geojson/occurrenceslist/",
        AllPublicationOccurrenceListGeoJsonView,
        name="all_publication_occurrenceslist_geojson",
    ),
    path(
        "map/occurrenceslist/",
        AllPublicationOccurrencesMap,
        name="map_all_publication_occurrenceslist",
    ),
    path(
        "list/occurrenceslist/", ListAllPublicationOccurrences, name="occurrenceslist"
    ),
    path("list/specieslist/", ListAllPublicationSpecies, name="specieslist"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from sysimibio.core.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sysimibio.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", home, name="home"),
    path(
        "imibio_occurrences/", include("sysimibio.imibio_occurrences.urls")
    ),  # todo cambiar a ingles
    path(
        "imibio_tree_ecological_data/",
        include("sysimibio.imibio_tree_ecological_data.urls"),
    ),  # todo cambiar a ingles
    path("bioblitz/", include("sysimibio.bioblitz.urls")),
    path("bibliography/", include("sysimibio.bibliography.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysimibio/bibliography/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from isbnlib import is_isbn10, to_isbn13

from sysimibio.bibliography.models import Publication, SpeciesList, OccurrenceList


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = "__all__"
        exclude = ("created_by",)

    def clean(self):
        cleaned_data = super().clean()
        doi = cleaned_data.get("DOI")
        isbn = cleaned_data.get("ISBN")
        crossref = cleaned_data.get("crossref")
        title = cleaned_data.get("title")
        author = cleaned_data.get("author")
        publication_year = cleaned_data.get("publication_year")

        if crossref and not doi and not isbn:
            raise ValidationError(
                "Ingresar DOI o ISBN. Si la publicacion no posee ninguno de los dos deshabilitar checkbox"
            )
        if not crossref and (not title or not author or not publication_year):
            raise ValidationError(
                "Si la publicacion no posee DOI ni ISBN, cargar Titulo, autor y año de publicacion"
            )

        return cleaned_data

    def clean_ISBN(self):
        isbn = self.cleaned_data.get("ISBN")
        if isbn:
            if is_isbn10(isbn):
                isbn = to_isbn13(isbn)
            if "-" in isbn:
                isbn = isbn.replace("-", "")
            if "." in isbn:
                isbn = isbn.replace(".", "")

        return isbn

    def clean_DOI(self):
        doi = self.cleaned_data.get("DOI")
        if doi.endswith("/"):
            doi = doi[:-1]
        return doi


class UploadSpeciesListForm(forms.ModelForm):
    species_list_spreadsheet = forms.FileField(
        validators=[FileExtensionValidator(["csv"])]
    )

    class Meta:
        model = SpeciesList
        exclude = (
            "scientific_name",
            "other_fields_json",
        )


class UploadOccurrencesListForm(forms.ModelForm):
    occurrences_list_spreadsheet = forms.FileField(
        validators=[FileExtensionValidator(["csv"])]
    )

    class Meta:
        model = OccurrenceList
        exclude = (
            "scientific_name",
            "latitude",
            "longitude",
            "other_fields_json",
        )

sysimibio/bibliography/views.py
from crossref.restful import Works
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render, resolve_url as r
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django_filters.views import FilterView
from djgeojson.views import GeoJSONLayerView
from isbnlib import is_isbn13, meta
from sysimibio.bibliography.filters import (
    PublicationFilters,
    SpeciesListFilters,
    OccurrenceListFilters,
)
from sysimibio.bibliography.forms import (
    PublicationForm,
    UploadSpeciesListForm,
    UploadOccurrencesListForm,
)
from sysimibio.bibliography.models import Publication, SpeciesList, OccurrenceList


class PublicationUpdateClass(LoginRequiredMixin, UpdateView):
    model = Publication
    form_class = PublicationForm

    def get_success_url(self):
        objectid = self.kwargs["pk"]
        return r("bibliography:publication_detail", objectid)


PublicationUpdateView = PublicationUpdateClass.as_view()


class PublicationListClass(LoginRequiredMixin, FilterView):
    paginate_by = 15
    queryset = Publication.objects.all().order_by("-publication_year")
    filterset_class = PublicationFilters
    template_name = "bibliography/publication_list.html"


PublicationList = PublicationListClass.as_view()


class PublicationDetailClass(LoginRequiredMixin, DetailView):
    model = Publication

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the
        context["species_list"] = SpeciesList.objects.filter(
            publication=self.kwargs["pk"]
        )
        context["occurrence_list"] = OccurrenceList.objects.filter(
            publication=self.kwargs["pk"]
        )
        return context


PublicationDetail = PublicationDetailClass.as_view()


class PublicationCreateClass(LoginRequiredMixin, CreateView):
    model = Publication
    form_class = PublicationForm

    def form_valid(self, form):
        self.publication = form.save(commit=False)
        self.publication.created_by = self.request.user
        works = Works()
        if self.publication.DOI != "" and works.doi_exists(self.publication.DOI):
            paper_data_result = works.doi(self.publication.DOI)
            self.publication.publication_year = str(
                paper_data_result.get("created").get("date-parts")[0][0]
            )
            self.publication.title = paper_data_result.get("title")[0]
            self.publication.author = f"{paper_data_result.get('author')[0].get('given')},{paper_data_result.get('author')[0].get('family')}"
            sub = paper_data_result.get("subject", [self.publication.subject])
            self.publication.subject = ", ".join([str(elem) for elem in sub])
            self.publication.URL = paper_data_result.get("URL")

        elif self.publication.ISBN != "" and is_isbn13(self.publication.ISBN):
            book_data_result = meta(self.publication.ISBN)
            self.publication.publication_year = book_data_result.get("Year")
            self.publication.title = book_data_result.get("Title")
            self.publication.author = book_data_result.get("Authors")[0]

        elif self.publication.crossref and (
            self.publication.DOI or self.publication.ISBN
        ):
            messages.error(
                self.request,
                'DOI/ISBN no encontrado. Cargar datos y desmarcar el campo "tiene DOI/ISBN"',
            )
            return render(
                self.request, "bibliography/publication_form.html", {"form": form}
            )
        self.publication.save()
        messages.success(self.request, "Registro realizado con exito")

        return redirect("bibliography:publication_detail", pk=self.publication.pk)


PublicationCreateView = PublicationCreateClass.as_view()


def handle_uploaded_species_list_file(file, publication_pk):
    import pandas as pd

    df = pd.read_csv(file)
    assert (
        "scientific_name" in df.columns
    ), "Archivo .CSV Inválido.Debe tener scientific_name como primera columna"
    columns_sequence = [number for number in range(1, len(df.columns))]
    result = pd.DataFrame()
    result["scientific_name"] = df.scientific_name
    result["publication"] = Publication.objects.get(pk=publication_pk)
    result = result.join(
        pd.DataFrame(
            {"other_fields_json": df.iloc[:, columns_sequence].to_dict("records")}
        )
    )
    return result


def handle_uploaded_ocurrences_list_file(file, publication_pk):
    import pandas as pd

    df = pd.read_csv(file)
    assert (
        "scientific_name" in df.columns
    ), "Archivo .csv Inválido.Falta columna scientific_name"
    assert "latitude" in df.columns, "Archivo .csv Inválido.Falta columna latitude"
    assert "longitude" in df.columns, "Archivo .csv Inválido.Falta columna longitude"
    columns_sequence = [number for number in range(3, len(df.columns))]
    result = pd.DataFrame()
    result["scientific_name"] = df.scientific_name
    result["latitude"] = df.latitude
    result["longitude"] = df.longitude
    result["publication"] = Publication.objects.get(pk=publication_pk)
    result = result.join(
        pd.DataFrame(
            {"other_fields_json": df.iloc[:, columns_sequence].to_dict("records")}
        )
    )
    return result


class SpeciesListCreateClass(LoginRequiredMixin, CreateView):
    model = Publication
    form_class = UploadSpeciesListForm

    def post(self, request, *args, **kwargs):
        form = UploadSpeciesListForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = (request.FILES["species_list_spreadsheet"],)
            publication_pk = request.POST["publication"]
            try:

                df = handle_uploaded_species_list_file(
                    file=uploaded_file[0], publication_pk=publication_pk
                )
                SpeciesList.objects.bulk_create(
                    SpeciesList(**vals) for vals in df.to_dict("records")
                )
            except AssertionError as e:
                messages.error(self.request, e)
                return render(
                    request, "bibliography/specieslist_form.html", {"form": form}
                )
            return HttpResponseRedirect(
                r("bibliography:publication_detail", publication_pk)
            )
        else:
            return render(request, "bibliography/specieslist_form.html", {"form": form})

    def get(self, request, *args, **kwargs):
        form = UploadSpeciesListForm()
        pk = self.kwargs.get(self.pk_url_kwarg)
        form.fields["publication"].queryset = Publication.objects.filter(pk=pk)
        return render(request, "bibliography/specieslist_form.html", {"form": form})


SpeciesListCreateView = SpeciesListCreateClass.as_view()


class SpeciesListUpdateClass(LoginRequiredMixin, UpdateView):
    model = Publication
    form_class = UploadSpeciesListForm

    def post(self, request, *args, **kwargs):
        form = UploadSpeciesListForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = (request.FILES["species_list_spreadsheet"],)
            publication_pk = request.POST["publication"]
            species_to_update = SpeciesList.objects.filter(publication=publication_pk)
            try:
                df = handle_uploaded_species_list_file(
                    file=uploaded_file[0], publication_pk=publication_pk
                )
                dict_list = [row for row in df.to_dict("records")]
                for index, obj in enumerate(list(species_to_update)):
                    dato = dict_list[index]
                    for key, value in dato.items():
                        setattr(obj, key, value)
                SpeciesList.objects.bulk_update(
                    species_to_update, ["scientific_name", "other_fields_json"]
                )
            except AssertionError as e:
                messages.error(self.request, e)
                return render(
                    request, "bibliography/specieslist_form.html", {"form": form}
                )
            return HttpResponseRedirect(
                r("bibliography:publication_detail", publication_pk)
            )
        else:
            return render(request, "bibliography/specieslist_form.html", {"form": form})

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        form = UploadSpeciesListForm()
        form.fields["publication"].queryset = Publication.objects.filter(pk=pk)
        return render(request, "bibliography/specieslist_form.html", {"form": form})


SpeciesListUpdateView = SpeciesListUpdateClass.as_view()


class OccurrenceListCreateClass(LoginRequiredMixin, CreateView):
    model = Publication
    form_class = UploadOccurrencesListForm

    def post(self, request, *args, **kwargs):
        form = UploadOccurrencesListForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = (request.FILES["occurrences_list_spreadsheet"],)
            publication_pk = request.POST["publication"]
            try:
                df = handle_uploaded_ocurrences_list_file(
                    file=uploaded_file[0], publication_pk=publication_pk
                )
                OccurrenceList.objects.bulk_create(
                    OccurrenceList(**vals) for vals in df.to_dict("records")
                )
            except AssertionError as e:
                messages.error(self.request, e)
                return render(
                    request, "bibliography/occurrenceslist_form.html", {"form": form}
                )
            return HttpResponseRedirect(
                r("bibliography:publication_detail", publication_pk)
            )
        else:

sysimibio/bibliography/templates/bibliography/occurrencelist_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="row">
    <div class="col-sm">
        <form method="get">
            {{ filter.form }}
            <button type="button" class="btn btn-primary"> Filtrar </button>
        </form>
    </div>
    <div class="col-sm">
        <a role="button" class="btn navbar-btn btn-secondary fa fa-map-marker" aria-hidden="true" href="{% url 'bibliography:map_all_publication_occurrenceslist' %}">Mapa Ocurrencias</a>
    </div>
</div>
<table class = 'table table-striped'>
    <thead>
    <tr>
        <th>Nombre científico</th>
        <th>Publicación</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Otros campos</th>
        <th>Fecha de creación</th>
    </tr>
    </thead>

    {% for occurrence in object_list %}

     <tr>
         <td>
             {{ occurrence.scientific_name }}
         </td>
         <td>
             <a href="{% url 'bibliography:publication_detail' pk=occurrence.publication.pk %}"style="color:black;">{{ occurrence.publication }}</a>
         </td>
         <td>
             {{ occurrence.longitude }}
         </td>
         <td>
             {{ occurrence.latitude }}
         </td>
         <td>
             {{ occurrence.other_fields_json }}
         </td>
         <td>
             {{ occurrence.publication.created_at }}
         </td>

     </tr>
{% endfor %}
        </table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a  role="button" class="btn navbar-btn btn-dark btn-sm"   <a href="?page=1"> Primera</a>
        <a  role="button" class="btn navbar-btn btn-dark btn-sm" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a  role="button" class="btn navbar-btn btn-dark btn-sm" <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        <a  role="button" class="btn navbar-btn btn-dark btn-sm"  <a href="?page={{ page_obj.paginator.num_pages }}">Ultima</a>
        {% endif %}
    </span>
</div>

{% endblock %}

sysimibio/bibliography/templates/bibliography/occurrencelist_map.html
{% load static %}
{% load leaflet_tags %}

{% block js %}
{% leaflet_js %}
{% endblock %}

{% block css %}
{% leaflet_css %}
{% endblock %}

{% block content %}

<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

      <title>SysIMiBio</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  body {
  margin-top:0px;
  padding-top: 75px;
  padding-bottom: 0px;
  }
    #map {
        height:100%;
        width:100%;
        }

</style>

  </head>
  <body>
    {% include "includes/nav.html" %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

    {% leaflet_map "map" %}

<script>
      var dataurl = '{% url "bibliography:all_publication_occurrenceslist_geojson" %}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });


</script>

{% endblock content %}

sysimibio/bibliography/templates/bibliography/occurrenceslist_form.html
{% extends 'base.html' %}

{% block content %}
<div class = "jumbotron">
    <div class = "container">
        <h2>Agregar Lista de ocurrencias</h2>
        {% if form.non_field_errors  %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        <p>{{ message }}</p>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

            <div class="accordion" id="accordionExample">
            <form method="POST" action="." class="post-form" enctype="multipart/form-data">
              {% csrf_token %}
          <div class="card ">
            <div class="card-header" id="headingOne">
              <h3 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  Datos de la lista
                </button>
              </h3>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card-body">
                  <p>
                      <label for="{{ form.bibliography.id_for_label }}"> {{ form.publication.label }} </label>
                      {% for error in form.publication.errors %}
                        <div class="alert alert-warning" role="alert">
                            {{ error }}
                        </div>
                      {% endfor %}
                      {{ form.publication}}
                  </p>
                  <p>
                      <label for="{{ form.occurrences_list_spreadsheet.id_for_label }}"> {{ form.occurrences_list_spreadsheet.label }}  </label>
                      {% for error in form.occurrences_list_spreadsheet.errors %}
                        <div class="alert alert-warning" role="alert">
                            {{ error }}
                        </div>
                      {% endfor %}
                      {{ form.occurrences_list_spreadsheet }}
                  </p>

              </div>
            </div>
          </div>


            <br><button type="submit" class="btn btn-success">Guardar</button>



        </form>
    </div>
</div>
</div>
{% endblock %}

sysimibio/bibliography/templates/bibliography/publication_detail.html
{% extends 'base.html' %}

{% load leaflet_tags %}

{% load static %}

{% block js %}
{% leaflet_js %}
{% endblock %}

{% block css %}
{% leaflet_css %}
{% endblock %}

{% block content %}

<style>
    #map-detail {
        width: 100%;
        height: 100%;
    }

</style>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}


<br>
<a role="button" class="btn navbar-btn btn-success" href="{% url 'bibliography:publication_list' %}">Volver a lista</a>
<a role="button" class="btn navbar-btn btn-warning" href="{% url 'bibliography:publication_edit' pk=publication.pk %}">Editar</a>
<br>

<h1>Titulo: {{ publication.title }}</h1>
<div class="row">
    <div class="col-sm-4">
        <table class="table table-user-information">
            <tbody>
            <tr>
                <th class="text-right">Autor principal:</th>
                <td>{{ publication.author }}</td>
            </tr>
            <tr>
                <th class="text-right">Año de publicación:</th>
                <td>{{ publication.publication_year }}</td>
            </tr>
            <tr>
                <th class="text-right">Participación de IMIBIO:</th>
                <td>{{ publication.imibio|yesno:"Si,No" }}</td>
            </tr>
            {% if publication.DOI %}
            <tr>
                <th class="text-right">DOI:</th>
                <td>{{ publication.DOI }}</td>
            </tr>
            {% endif %}

            {% if publication.ISBN %}
            <tr>
                <th class="text-right">ISBN:</th>
                <td>{{ publication.ISBN }}</td>
            </tr>
            {% endif %}

            <tr>
                <th class="text-right">Temas o palabras clave:</th>
                <td>{{ publication.subject }}</td>
            </tr>
            {% if publication.URL %}
            <tr>
                <th class="text-right">URL:</th>
                <td><a href="{{ publication.URL }}">{{ publication.URL }}</a></td>
            </tr>
            {% endif %}
            {% if publication.observations %}
            <tr>
                <th class="text-right">Observaciones:</th>
                <td><p>{{ publication.observations }}</p></td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
    <div class="col-sm-8">
        <div id="map-detail">
            {% leaflet_map "map-detail" %}
        </div>
    </div>
</div>
<br>
<p></p>
<div class="row">
    <div class="col">
        <div class="jumbotron">
        {% if  not species_list  %}
            <a role="button" class="btn navbar-btn btn-dark" href="{% url 'bibliography:specieslist_new' pk=publication.pk %}">Agregar Lista de especies</a>
        {% else %}
            <a role="button" class="btn navbar-btn btn-dark" href="{% url 'bibliography:specieslist_edit' pk=publication.pk %}">Editar Lista de Especies</a>
            <h2>Lista de especies</h2>
            <table class='table table-striped'>
                <thead>
                <tr>
                    <th>Nombre científico</th>
                    <th>otras columnas</th>
                </tr>
                </thead>

                {% for specie in species_list %}
                <tr>
                    <td>
                        {{ specie.scientific_name }}</a>
                    </td>
                    <td>
                        {{ specie.other_fields_json}}
                    </td>
                </tr>
                {% endfor %}

            </table>
        {% endif %}
        </div>
    </div>

    <div class="col">
        <div style="background:darkgrey" class="jumbotron">
        {% if  not occurrence_list  %}
            <a role="button" class="btn navbar-btn btn-dark" href="{% url 'bibliography:occurrenceslist_new' pk=publication.pk %}">Agregar lista de ocurrencias</a>
        {% else %}
            <a role="button" class="btn navbar-btn btn-dark" href="{% url 'bibliography:occurrenceslist_edit' pk=publication.pk %}">Editar Lista de Ocurrencias</a>
            <h2>Lista de occurrencias</h2>
            <table class='table table-striped'>
                <tbody>
                <tr>
                    <th>Nombre científico</th>
                    <th>Longitud</th>
                    <th>Latitud</th>
                    <th>otras columnas</th>
                </tr>
                {% for occurrence in occurrence_list %}
                <tr>
                    <td>
                        {{ occurrence.scientific_name }}</a>
                    </td>
                    <td>
                        {{ occurrence.longitude }}</a>
                    </td>
                    <td>
                        {{ occurrence.latitude }}</a>
                    </td>
                    <td>
                        {{ occurrence.other_fields_json}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        </div>
    </div>

</div>
<script>
      var dataurl = '{% url "bibliography:publication_occurrenceslist_geojson" pk=publication.pk%}';
      window.addEventListener("map:init", function (event) {
        var map = event.detail.map;
        // Download GeoJSON data with Ajax
        fetch(dataurl)
          .then(function(resp) {
            return resp.json();
          })
          .then(function(data) {
            L.geoJson(data, {
              onEachFeature: function onEachFeature(feature, layer) {
                var props = feature.properties.popup_content;
                layer.bindPopup(props);
            }}).addTo(map);
          });
      });


</script>

{% endblock content %}

sysimibio/bibliography/templates/bibliography/publication_list.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="row">
    <div class="col-sm">
        <form method="get">
            {{ filter.form }}
            <button type="submit" class="btn btn-primary" > Filtrar </button>
        </form>
    </div>
    <div class="col-sm">
        <a role="button" class="btn navbar-btn btn-secondary fa fa-map-marker" aria-hidden="true" href="{% url 'bibliography:map_all_publication_occurrenceslist' %}">Mapa Ocurrencias</a>
    </div>
</div>
<br>
<table class = 'table table-striped'>
    <thead>
    <tr>
        <th>Título</th>
        <th>AÑO</th>
        <th>CONTRIBUCIÓN IMIBIO </th>
        <th>TIPO</th>
    </tr>
    </thead>

    {% for publication in filter.qs %}

     <tr>
         <td>
             <a href="{% url 'bibliography:publication_detail' pk=publication.pk %}"style="color:black;">{{ publication.title }}</a>
         </td>
         <td>
             {{ publication.publication_year}}
         </td>
         <td>
             {{ publication.imibio|yesno:"Si,No" }}
         </td>
         <td>
             {% if publication.DOI %}
                Articulo
             {% else %}
                Libro
             {% endif %}
         </td>
     </tr>
{% endfor %}
        </table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a  role="button" class="btn navbar-btn btn-dark btn-sm"   <a href="?page=1"> Primera</a>
        <a  role="button" class="btn navbar-btn btn-dark btn-sm" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a  role="button" class="btn navbar-btn btn-dark btn-sm" <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        <a  role="button" class="btn navbar-btn btn-dark btn-sm"  <a href="?page={{ page_obj.paginator.num_pages }}">Ultima</a>
        {% endif %}
    </span>
</div>

{% endblock %}